### ISSUE TITLE
Injecting Symfony service container

### ISSUE THREAD

**Issue by bouke-nederstigt** [odesk/phystrix-bundle#1]
Hi,

Currently I am using the phystrix-bundle in a Symfony project. I was wondering what the best way would be to inject the Symfony service container into my commands. I think just overwriting the CommandFactory doesn't solve the problem because the AbstractCommand's function setServiceLocator also expects an instance of Zend LocatorInterface. 

My current solution is to extend the Command Factory as well as the abstract command and add an extra variable serviceContainer, which holds the service_container. However, this all seems a bit hacky. Any suggestions? 

Kind regards,

Bouke

**Comment by lcf** [comment]
Hi Bouke,

You can inject Symfony service container itself into the one used by Phystrix. You can do so manually:

```
$container->get('phystrix.service_locator')->set('container', $symfonyServiceContainer);
```

or, you can choose to inject only the dependencies your commands will need, which is what we do. For example:

```
$container->get('phystrix.service_locator')->set('db', $dbConnection);
$container->get('phystrix.service_locator')->set('logger', $logger);
```

You can also create a "ServiceLocotarPass" using Symfony's CompilerPass DI feature, something like this:

```
class ServiceLocatorPass implements CompilerPassInterface
{

    public function process(ContainerBuilder $container)
    {
        $container->getDefinition('phystrix.service_locator')
            ->addMethodCall('set', array('db', new Reference('bouke.db.connection')))
            ->addMethodCall('set', array('logger', new Reference('bouke.utils.logger')));
    }
}
```

so it will happen behind the scenes, right after symfony di container compilation.

**Comment by bouke-nederstigt** [comment]
Ah of course. That's a much cleaner solution. Thanks for the quick reply!

**Comment by lcf** [comment]
My pleasure
