### ISSUE TITLE
Symfony Fullstack Requirement

### ISSUE THREAD

**Issue by immutef** [odesk/phystrix-bundle#3]
I'd suggest not to require the Symfony fullstack framework but only bundles/compoments the bundle needs (including splitting these into require/require-dev accordingly).

I've had several problems because of that constraint to integrate it within our projects :(

**Comment by lcf** [comment]
@pminnieur sounds reasonable. Can you submit a pull request?

**Comment by immutef** [comment]
Yeah I may take a look over the weekend.

**Comment by mxnr** [comment]
Hey @pminnieur, we have already done such changes internally, the release with update will be available soon!

**Comment by lcf** [comment]
new release tagged, I hope this helps and thank you for your contribution @pminnieur !

**Comment by immutef** [comment]
Thanks @lcf I'll take a look soon, since I was on a vacation :-)
